# Generated by Django 4.1.5 on 2023-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='open_at',
            field=models.DateTimeField(),
        ),
    ]
