# Generated by Django 4.1.5 on 2023-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_open_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='open_at',
            field=models.CharField(max_length=50),
        ),
    ]
