# Generated by Django 4.1.5 on 2023-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verf_user',
            field=models.BooleanField(default=False),
        ),
    ]
