# Generated by Django 4.1.5 on 2023-01-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compinformation', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='info',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='compinformation.informations'),
            preserve_default=False,
        ),
    ]
